build:
    environment:
        php:
            version: 8.3.3
            ini:
                xdebug.mode: coverage
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'

before_commands:
    - git --version
    - git config --global user.email "git-elephant@scrutinizer-ci.com"
    - git config --global user.name "git-elephant"
    - composer install

filter:
    excluded_paths:
        - 'vendor/*'

tools:
    php_code_sniffer:
        enabled: true
        filter:
            paths: [ src/ ]
        config:
            # Built-in standards: PEAR, PHPCS, PSR1, PSR2, Squiz, Zend
            standard: PSR2
    php_cpd:
        enabled: true
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
        filter:
            paths: [ src/ ]
    php_mess_detector:
        enabled: true
        filter:
            paths: [ src/ ]
    php_analyzer: true
    sensiolabs_security_checker: false
    php_pdepend: true
    php_loc: true
