name: Code Style Check

on:
  push:
  pull_request:

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          coverage: none
      - run: composer install --no-progress
      # fix code style, automatically
      - run: composer fix-cs
      # push changes back
      # note that this might not work with PRs from forks:
      # https://github.com/stefanzweifel/git-auto-commit-action/issues/25
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatic Fix of Code Style
          branch: ${{ github.head_ref || github.ref_name }}

      # check if some unfixable code style issues remain
      - run: composer check-cs
