name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "7.4"
          - "8.0"
        symfony:
          - 5.*
          - 6.*
        dependency-version:
          # - prefer-lowest
          - prefer-stable
        exclude:
          - {php: "7.4", symfony: "6.*"}
          - {php: "8.0", symfony: "3.*"}

    name: PHP ${{ matrix.php }} - S ${{ matrix.symfony }} - ${{ matrix.dependency-version }} - tests
    steps:
      # basically git clone
      - uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git --version
          git config --global user.email "test@github.com"
          git config --global user.name "GitHub Action"
          git --version

      - name: Setup PHP
        # use PHP of specific version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none # disable xdebug, pcov
          tools: composer

      - name: Install Composer Dependencies
        run: |
          composer require "symfony/process:${{ matrix.symfony }}" "symfony/filesystem:${{ matrix.symfony }}" "symfony/finder:${{ matrix.symfony }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Run PHPUnit Tests
        run: composer tests
